name: Build and Deploy Demo App (.NET)

on:
  push:
    branches:
      - main

env:
  APP_NAME: dummy-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Simulate Build
        run: echo "No .NET project found — skipping build"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
