name: Build and Deploy Python App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      APP_NAME: dummy-python-app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # ✅ Deployment Step (real or simulated)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        continue-on-error: true

      - name: Simulate Deployment (if no Azure credentials)
        if: failure()
        run: echo "✅ Simulated deployment for Python app"
